[workspace]
resolver = "2"
members = [ "aggregator","plasma-fold", "client"]

[workspace.dependencies]
ark-ff = { version = "^0.5.0" }
ark-bn254 = { version = "0.5.0", features = ["r1cs"] }
ark-grumpkin = { version = "0.5.0", features = ["r1cs"] }

[patch.crates-io]
ark-r1cs-std = { git = "https://github.com/yelhousni/r1cs-std", rev = "440ca3" }
